version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on: ["mongo"]
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on: ["mongo"]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
